package internal

import (
	"fmt"
	"os"
	"strings"

	"github.com/charmbracelet/bubbles/textinput"
	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

var blueColor = "#A4D6F4"
var yellowColor = "#F0D7AE"
var grayColor = "#737373"

var (
	focusedStyle = lipgloss.NewStyle().Foreground(lipgloss.Color(blueColor))
	blurredStyle = lipgloss.NewStyle().Foreground(lipgloss.Color(grayColor))
	cursorStyle  = focusedStyle.Copy()
	noStyle      = lipgloss.NewStyle()
	helpStyle    = blurredStyle.Copy()

	focusedButton = focusedStyle.Copy().Render("[ Submit ]")
	blurredButton = fmt.Sprintf("[ %s ]", blurredStyle.Render("Submit"))
)

type model struct {
	config     Config
	cursor     int
	selected   *int
	topButtons []string

	inputsQuery []textinput.Model
	inputsDB    []textinput.Model
	focusIndex  int
}

var filePath string

func checkConfig() tea.Msg {
	root, _ := os.UserHomeDir()
	filePath = fmt.Sprintf("%s/.config/sqlal/config.json", root)
	_, err := os.Stat(filePath)

	if err != nil {
		config := NewDefaultConfig()
		config.SaveToFile(filePath)

		return config
	}

	config := Config{}
	config.LoadFromFile(filePath)

	return config
}

func InitialModel() model {
	m := model{
		selected:    nil,
		topButtons:  []string{"Configure database", "Create new query\n"},
		inputsQuery: make([]textinput.Model, 3),
	}

	m.SetInputs()

	return m
}

func (m *model) SetInputs() {
	var t textinput.Model
	for i := range m.inputsQuery {
		t = textinput.New()
		t.Cursor.Style = cursorStyle
		t.CharLimit = 512

		switch i {
		case 0:
			t.Placeholder = "Name"
			t.Focus()
			t.PromptStyle = focusedStyle
			t.TextStyle = focusedStyle
		case 1:
			t.Placeholder = "SQL"
		case 2:
			t.Placeholder = "URL"
		}

		m.inputsQuery[i] = t
	}
}

func (m model) Init() tea.Cmd {
	return checkConfig
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case Config:
		m.config = Config(msg)
		return m, nil
	case tea.KeyMsg:
		if m.selected != nil {
			return m.handleInputsKey(msg)
		} else {
			return m.handleConfigMenuKey(msg)
		}
	}

	return m, nil
}

func (m *model) handleInputsKey(msg tea.KeyMsg) (tea.Model, tea.Cmd) {
	switch msg.String() {
	case "ctrl+c", "esc":
		m.selected = nil
		m.focusIndex = 0

		return m, nil
	case "tab", "shift+tab", "enter", "up", "down":
		return m.navigateInputs(msg.String())
	}
	return m, m.updateInputs(msg) // Return the updated model and the commands generated by inputs
}

func (m model) handleConfigMenuKey(msg tea.KeyMsg) (tea.Model, tea.Cmd) {
	switch msg.String() {
	case "ctrl+c", "q":
		return m, tea.Quit
	case "x":
		return m.deleteQuery()
	case "up", "k":
		return m.moveCursorUp()
	case "down", "j":
		return m.moveCursorDown()
	case "enter", " ":
		return m.toggleSelected()
	}
	return m, nil
}

func (m model) navigateInputs(s string) (tea.Model, tea.Cmd) {
	if s == "enter" && m.focusIndex == len(m.inputsQuery) {
		if m.selected != nil && *m.selected >= len(m.topButtons) {
			queryIndex := *m.selected - len(m.topButtons)
			newQuery := QueryConfig{
				Name:            m.inputsQuery[0].Value(),
				Query:           m.inputsQuery[1].Value(),
				NotificationURL: m.inputsQuery[2].Value(),
			}
			m.config.UpdateQuery(queryIndex, newQuery)
			m.config.SaveToFile(filePath)
			m.SetInputs()
		} else {
			newQuery := QueryConfig{
				Name:            m.inputsQuery[0].Value(),
				Query:           m.inputsQuery[1].Value(),
				NotificationURL: m.inputsQuery[2].Value(),
			}
			m.config.AddQuery(newQuery)
			m.config.SaveToFile(filePath)
			m.SetInputs()
		}

		m.selected = nil
		m.focusIndex = 0

		return m, nil
	}

	// Cycle indexes
	if s == "up" || s == "shift+tab" {
		m.focusIndex--
	} else {
		m.focusIndex++
	}

	if m.focusIndex > len(m.inputsQuery) {
		m.focusIndex = 0
	} else if m.focusIndex < 0 {
		m.focusIndex = len(m.inputsQuery)
	}

	cmds := make([]tea.Cmd, len(m.inputsQuery))
	for i := 0; i <= len(m.inputsQuery)-1; i++ {
		if i == m.focusIndex {
			// Set focused state
			cmds[i] = m.inputsQuery[i].Focus()
			m.inputsQuery[i].PromptStyle = focusedStyle
			m.inputsQuery[i].TextStyle = focusedStyle
			continue
		}
		// Remove focused state
		m.inputsQuery[i].Blur()
		m.inputsQuery[i].PromptStyle = noStyle
		m.inputsQuery[i].TextStyle = noStyle
	}

	return m, tea.Batch(cmds...)
}

func (m model) deleteQuery() (tea.Model, tea.Cmd) {
	if m.cursor >= len(m.topButtons) {
		m.config.DeleteQueryByIndex(m.cursor - len(m.topButtons))
		m.config.SaveToFile(filePath)

		m.cursor = m.cursor - 1
	}

	return m, nil
}

func (m model) moveCursorUp() (tea.Model, tea.Cmd) {
	if m.cursor > 0 {
		m.cursor--
	} else {
		m.cursor = len(m.config.GetQueryNames()) + len(m.topButtons) - 1
	}

	return m, nil
}

func (m model) moveCursorDown() (tea.Model, tea.Cmd) {
	if m.cursor < len(m.config.GetQueryNames())+len(m.topButtons)-1 {
		m.cursor++
	} else {
		m.cursor = 0
	}

	return m, nil
}

func (m *model) toggleSelected() (tea.Model, tea.Cmd) {
	if m.cursor < len(m.topButtons) {
		m.selected = &m.cursor
		clearInputs(m.inputsQuery)
	} else {
		m.selected = &m.cursor
		setInputsFromQuery(&m.config, m.inputsQuery, m.cursor, len(m.topButtons))
	}
	return m, nil
}

func clearInputs(inputs []textinput.Model) {
	for i := range inputs {
		inputs[i].SetValue("")
	}
}

func setInputsFromQuery(config *Config, inputs []textinput.Model, cursor, topButtonLen int) {
	selectedIndex := cursor - topButtonLen
	if selectedIndex >= 0 && selectedIndex < len(config.Queries)+topButtonLen {
		query := config.Queries[selectedIndex]
		for i, input := range inputs {
			switch i {
			case 0:
				input.SetValue(query.Name)
			case 1:
				input.SetValue(query.Query)
			case 2:
				input.SetValue(query.NotificationURL)
			}
			inputs[i] = input
		}
	}
}

func (m *model) updateInputs(msg tea.Msg) tea.Cmd {
	cmds := make([]tea.Cmd, len(m.inputsQuery))

	// Only text inputs with Focus() set will respond, so it's safe to simply
	// update all of them here without any further logic.
	for i := range m.inputsQuery {
		m.inputsQuery[i], cmds[i] = m.inputsQuery[i].Update(msg)
	}

	return tea.Batch(cmds...)
}

func (m model) View() string {
	if m.shouldShowInputsView() {
		return m.renderInputsView()
	} else {
		return m.renderConfigMenuView()
	}
}

func (m model) shouldShowInputsView() bool {
	return m.selected != nil
}

func (m model) renderInputsView() string {
	var b strings.Builder

	if *m.selected >= len(m.topButtons) {
		renderInputs(&b, m.inputsQuery)
	}
	if *m.selected < len(m.topButtons) {
		renderAndResetInputs(&b, m.inputsQuery)
	}

	renderButton(&b, m.focusIndex == len(m.inputsQuery))

	return b.String()
}

func renderInputs(b *strings.Builder, inputs []textinput.Model) {
	for i, input := range inputs {
		b.WriteString(input.View())
		if i < len(inputs)-1 {
			b.WriteRune('\n')
		}
	}
}

func renderAndResetInputs(b *strings.Builder, inputs []textinput.Model) {
	for i, input := range inputs {
		b.WriteString(input.View())
		if i < len(inputs)-1 {
			b.WriteRune('\n')
		}
	}
}

func renderButton(b *strings.Builder, isFocused bool) {
	button := &blurredButton
	if isFocused {
		button = &focusedButton
	}
	fmt.Fprintf(b, "\n\n%s\n\n%s\n", *button, helpStyle.Render("[enter] - submit; [esc] - go back;"))
}

func (m model) renderConfigMenuView() string {
	s := lipgloss.NewStyle().Foreground(lipgloss.Color("#A4F4D7")).Render("SQL Alerts configuration menu") + "\n\n"

	var cursor string
	for i, button := range m.topButtons {
		cursor = " "
		if m.cursor == i {
			cursor = ">"
			lipgloss.NewStyle().Foreground(lipgloss.Color(blueColor)).Render(button)
		}
		s += fmt.Sprintf("%s %s\n", lipgloss.NewStyle().Foreground(lipgloss.Color(blueColor)).Render(cursor), button)
	}

	for i, choice := range m.config.GetQueryNames() {
		cursor = " "
		if m.cursor == i+len(m.topButtons) {
			cursor = ">"
			choice = lipgloss.NewStyle().Foreground(lipgloss.Color(yellowColor)).Render(choice)
		}
		s += fmt.Sprintf("%s %s\n", lipgloss.NewStyle().Foreground(lipgloss.Color(blueColor)).Render(cursor), choice)
	}

	if m.cursor < len(m.topButtons) {
		s += helpStyle.Render("\n\n[enter] - open; [q] - quit;\n")
	} else {
		s += helpStyle.Render("\n\n[enter] - edit; [x] - delete; [q] - quit;\n")
	}

	return s
}
